name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

on:
  push:
    paths:
    - '**__version__.py'

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Verify that the package installs from source.
      run: |
        pip install .
        VERSION=$(python -c 'from gpseer.__version__ import __version__; print("v" + __version__)')
    - name: Publish distribution ğŸ“¦ to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.GH_actions_PyPI_token }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Tag this version
      run: |
        git tag VERSION
    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}